### PR TITLE
FoldingRange

### PR DESCRIPTION
**Pull request by billyeatcookies**

### CODE REVIEW

**Comment by billyeatcookies** [comment]
sorry this pr was opened by accident, pushed to upstream.

**Comment by Akuli** [comment]
Tarts seems interesting. I probably want to use it, and I think some others would too. As far as I know, sansio-lsp-client has been used in at least two editors (soon 3 if we count your editor) and one other thing.

Do you want us to merge your changes back to sansio-lsp-client eventually, or do you want to maintain your own fork, so that me (and maybe PurpleMyst) just make pull requests to tarts, and we eventually archive this repo? If you don't want to merge your changes back to sansio-lsp-client, can you at least enable the github issue tracker for tarts? I don't want to make a fork of tarts.

**Comment by PurpleMyst** [comment]
Got an e-mail about this :eyes:, looks like you integrated some of the newer parts of the LSP spec into the codebase. If you're interested, merging that back upstream would be rather nice! I've noticed you use match statements though, and I'm not sure that our library's consumers want to bump their minimum Python version. @Akuli should make the call here, but definitely do let us know if you're interested in merging this back.

**Comment by Akuli** [comment]
I did think of the match statements too, but decided that I don't really care (for my projects) as the latest stable ubuntu comes with Python 3.10 now.

**Comment by billyeatcookies** [comment]
@Akuli @PurpleMyst As the project has been inactive for two years, I assumed it got discontinued and it would be pointless opening pr on the new features my little editor project required out of the client (like folding ranges, inlay hints, rename... so far). But yes surely I am willing to contribute to sansio-lsp-client instead of working on the fork if you guys are still maintaining it, would love to hear that ❤️

**Comment by Akuli** [comment]
Indeed, it is still reasonably maintained. We review and merge whenever someone makes a pull request, and getting your changes here would be great :) You wouldn't be the first person to initially fork this project, add a bunch of features, and then decide to get them merged back here (#39 / #41).

This project won't go entirely unmaintained any time soon. It is used in Porcupine and I use porcupine daily, so if this project was somehow completely broken/unusable, it would kinda force me to fix it. That said, Porcupine doesn't force me to do a *great* job maintaining this project, e.g. there's not much documentation, and new features don't usually get implemented until someone else does the work.

**Comment by PurpleMyst** [comment]
Glad to hear you're willing to contribute back! Perhaps it's time to add a "hey, this is in maintenance mode" notice to the README.md?

**Comment by billyeatcookies** [comment]
@Akuli glad to hear that! got chills from hearing that for daily use cases you are using the editor you wrote, that definitely feels awesome xd. I will open a new pr with restored project data parts, I tried to fix the workflows but unfortunately couldn't find a supported pydantic-v1 package. So far tried the original and `1.10.14` which apparently installed fine in my system, but [failed in github workflows](https://github.com/billyeatcookies/tarts/actions/runs/7600941316/job/20699750818).

**Comment by Akuli** [comment]
> got chills from hearing that for daily use cases you are using the editor you wrote, that definitely feels awesome xd.

It seems like you aren't far away from this either, especially with langserver support :) I recommend installing the latest "stable" version of your editor into a separate place, so that you can use your editor even when you temporarily break it during development.

> I tried to fix the workflows but unfortunately couldn't find a supported pydantic-v1 package.

Feel free to update pydantic, if it helps any.

**Pull request closed without merging**
