### PR TITLE
More tests

### PR DESCRIPTION
**Pull request by Akuli**
- javascript-typescript-langserver test (works)
- clangd 10 test (works)
- clangd 11 test (fails, remove `@pytest.mark.xfail` to see failure)

### CODE REVIEW

**Comment by PurpleMyst** [comment]
What's the test failure for clangd11? I'm on Windows and I can't test in the present moment, I'll need to set up a test environment on my rPi

**Comment by Akuli** [comment]
I made a branch named `clangd11`. You can see the failure in its CI: https://github.com/PurpleMyst/sansio-lsp-client/runs/1700681334

**Comment by PurpleMyst** [comment]
> I[08:48:48.714] Failed to find compilation database for /tmp/pytest-of-runner/pytest-0/test_clangd_110/foo.c
^ Is this the error that makes it fail?
v or this one?
> E[08:48:48.777] Transport error: Input/output error

**Comment by Akuli** [comment]
I meant this error:

```
E   pydantic.error_wrappers.ValidationError: 2 validation errors for CompletionList
E   items -> 2 -> documentation
E     str type expected (type=type_error.str)
E   items -> 3 -> documentation
E     str type expected (type=type_error.str)
```

**Comment by PurpleMyst** [comment]
Does this still happen after the changes in 79770bdc4d234a614cedd33dc8587f8405ffcba5?

**Comment by Akuli** [comment]
No. Those tests passed.

**Comment by PurpleMyst** [comment]
Perfect. We can remove the xfail then

**Comment by Akuli** [comment]
Lol, I forgot that I xfailed it...

xfail means that if the test fails, it's marked as success, and vice versa. So I was wrong, it still happens.

**Comment by PurpleMyst** [comment]
oop

this is probably the cause
https://github.com/PurpleMyst/sansio-lsp-client/blob/master/sansio_lsp_client/structs.py#L166-L167

**Pull request merged**
