### PR TITLE
fix mypy errors

### LINKED ISSUE #9: doesn't work with mypy
```
$ python3.7 -m venv env
$ . env/bin/activate
(env) $ pip install sansio-lsp-client
...
Successfully installed attrs-18.2.0 cattrs-0.9.2 sansio-lsp-client-0.6.1
(env) $ pip install mypy
...
Successfully installed mypy-0.782 mypy-extensions-0.4.3 typed-ast-1.4.1 typing-extensions-3.7.4.2
(env) $ echo import sansio_lsp_client > hello.py
(env) $ mypy hello.py
hello.py:1: error: Skipping analyzing 'sansio_lsp_client': found module but no type hints or library stubs
hello.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

i'm a bit confused because there are type hints in `sansio_lsp_client`

### PR DESCRIPTION
**Pull request by Akuli**
- fixed all mypy errors i could fix, one error left
- run `mypy --strict` on github actions
- run `black --check` on github actions

closes #9

### CODE REVIEW

**Comment by Akuli** [comment]
what about the `FIXME`? do you remember what type it's supposed to be?

**Comment by Akuli** [comment]
now you can read the errors on github actions

**Comment by PurpleMyst** [comment]
That FIXME is, theoretically, unfixable. The result attribute on Response's type is defined as JSONDict, which, due to mypy not being able to properly represent recursive types (which the type of a JSON dictionary is), is just simply defined as a dictionary from a string key to any type of value. So this results in a mismatch between the JSON actually being a list, but being described in types as a dictionary.

A workaround could be describing JSONDict as an Union between Dict[str, Any] and List[Any], but I think that'd break other stuff.

¯\_(ツ)_/¯

**Comment by Akuli** [comment]
Should `response.result` be turned into a list of instances of some non-Any-typed classes before adding it to the event lists that goes to the user of the library?

**Comment by PurpleMyst** [comment]
I'm not sure what you mean?

**Comment by Akuli** [comment]
Most events have instances of classes decorated with `@attr.s` as all of their attributes, but `WillSaveWaitUntilEdits` has a list of loosely typed dicts.

**Comment by PurpleMyst** [comment]
while response.result's type annotation *says* it is a json dict, not all response's result are *actually* json dictionaries, some are lists or null or other things. this is one of those cases.

**Comment by PurpleMyst** [comment]
we could just [cast](https://docs.python.org/3/library/typing.html#typing.cast) it, as the type is correct at runtime

**Pull request merged**
