### PR TITLE
Header parsing fixes: default content-type, case insensitivity

### PR DESCRIPTION
**Pull request by Akuli**

### CODE REVIEW

**Comment by Akuli** [comment]
This pull request makes this thing actually work with clangd

**Comment by PurpleMyst** [comment]
Looks good to me, although I hate how the spec is more like a.. guideline. I'm going to merge this, but could you please check out what Microsoft's "official" LSP client's behavior is?

**Comment by Akuli** [comment]
I don't want to use Microsoft products, but anything that works with `clangd` must guess `Content-Type`.

**Comment by PurpleMyst** [comment]
LSP is, to some degree, a Microsoft product and they provide the official libraries for it (for node.js), and the behavior of their libraries pretty much supercedes the spec.

**Comment by Akuli** [comment]
Can you upload to pypi?

**Comment by Akuli** [comment]
looking at github actions logs, this needs a version bump to get automatically updated

**Pull request merged**
